Add integration with Grafana Agent
canonical/openstack-exporter-operator pull request #11
Opened 2024-03-20 04:38 UTC by samuelallan72

Add integration with Grafana Agent

- pull in the cos_agent interface library
- configure the relation with path and port for openstack-exporter metrics

## Testing

Some helpful commands for testing:

```
charmcraft -v pack
juju deploy ./openstack-exporter_ubuntu-22.04-amd64.charm --resource openstack-exporter=golang-openstack-exporter_1.6.0_amd64.snap
juju deploy grafana-agent
juju relate openstack-exporter grafana-agent
```

2024-03-20 05:54 UTC, chanchiwai-ray requested changes

2024-03-20 05:54 UTC, chanchiwai-ray commented on src/charm.py
> +        self._grafana_agent = COSAgentProvider(
It's worth thinking should we start the snap service without this relation. We generally think the exporter service should be started only when it's required (i.e. there is consumers for the metric). Can you add some logic in the `configure` method to properly handle that?

2024-03-20 09:27 UTC, chanchiwai-ray requested changes

2024-03-20 09:27 UTC, chanchiwai-ray commented on CONTRIBUTING.md
Thanks for the doc updates, can you move this to a separate PR? I need these to create workflow for automatic updating the libs

2024-03-20 09:27 UTC, chanchiwai-ray commented on update_charm_libs.sh
Also move this to a new PR

2024-03-21 02:17 UTC, chanchiwai-ray submitted a review, later dismissed
LGTM, thanks

2024-03-21 02:17 UTC, chanchiwai-ray commented on CONTRIBUTING.md
Thanks

2024-03-21 04:21 UTC, jneo8 approved these changes

2024-03-21 05:54 UTC, chanchiwai-ray approved these changes

2024-03-21 06:09 UTC, jneo8 approved these changes

2024-03-21 06:13 UTC, merged