test: Setup openstack environemnt for testing
canonical/openstack-exporter-operator pull request #40
Opened 2024-04-11 07:50 UTC by jneo8

2024-04-12 10:44 UTC, rgildein reviewed
To me, this looks good if we address @samuelallan72 comments.

2024-04-18 06:26 UTC, chanchiwai-ray requested changes

2024-04-18 06:26 UTC, chanchiwai-ray commented on tests/integration/tests/bundles/jammy.yaml
Can you be specific about what release is this openstack bundle? (yoga / bobcat) in the filename, and also for each openstack charm

2024-04-18 06:51 UTC, jneo8 commented on tests/integration/tests/bundles/jammy.yaml
you would like to have `jammy-yoga.yaml` instead of `jammy.yaml`? I think it's ok.
But the revision is one thing I don't want to pin in the bundle, only provide channel.

2024-04-18 06:52 UTC, jneo8 commented on tests/integration/tests/bundles/jammy.yaml
> +    revision: 137
Let me remove them all.

2024-04-18 07:02 UTC, jneo8 commented on tests/integration/tests/bundles/jammy.yaml
> +      osd-devices: ""
Removed.

2024-04-18 08:22 UTC, chanchiwai-ray approved these changes

2024-04-18 09:05 UTC, chanchiwai-ray approved these changes

2024-04-18 10:19 UTC, Pjack approved these changes

2024-04-18 10:21 UTC, merged